# -*- coding: utf-8 -*-
"""calculadora_v01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U-SaGBu1Swgv46JCg8LAGwoosKLAF4at
"""
# Função de Soma
def op1(num1, num2):
  soma = num1 + num2
  print("%d + %d = %d" %(num1, num2, soma))

# Função de Subtração
def op2(num1, num2):
  sub = num1 - num2
  print("%d - %d = %d" %(num1, num2, sub))

# Função de Multiplicação
def op3(num1, num2):
  mult = num1 * num2
  print("%d * %d = %d" %(num1, num2, mult))

# Função de Divisão
def op4(num1, num2):
  div = num1 / num2
  print("%d / %d = %d" %(num1, num2, div))

# Calculadora em Python
print("\n******************* Python Calculator *******************")
# Mostrar as opções disponíveis para o usuário
print("\n*********** Favor escolher uma das opções abaixo ***********")
print("\n 1- Soma")
print(" 2- Subtração")
print(" 3- Multiplicação")
print(" 4- Divisão")

# Receber as variaveis do usuário e valida-las (opção)
opcao = int(input("Digite uma opção de Cálculo: "))

# Receber as variaveis do usuário (num1 e num2)
num1 = int(input("Digite Primeiro Número: "))
num2 = int(input("Digite Segundo Número: "))

# Condicional das funções
if (opcao == 1):
  op1(num1, num2)
elif (opcao == 2):
  op2(num1, num2)
elif (opcao == 3):
  op3(num1, num2)
elif (opcao == 4):
  op4(num1, num2)
elif(opcao != 1 or opcao != 2 or opcao != 3 or opcao != 4):
  print("\nInformação Inválida!")